version: '3.8'

services:
  # Database
  mysql:
    image: mysql:8.0
    container_name: nextbill-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: nextbill
      MYSQL_USER: nextbill
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - nextbill-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Cache
  redis:
    image: redis:7-alpine
    container_name: nextbill-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - nextbill-network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      timeout: 20s
      retries: 10

  # Message Queue
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: nextbill-zookeeper
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - nextbill-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: nextbill-kafka
    restart: unless-stopped
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://nextbill-kafka:29092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
    ports:
      - "9092:29092"
    networks:
      - nextbill-network
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:29092"]
      timeout: 20s
      retries: 10

  # Backend API (빌드 최적화)
  nextbill-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextbill-backend
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://nextbill-mysql:3306/nextbill?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: nextbill
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      SPRING_REDIS_HOST: nextbill-redis
      SPRING_REDIS_PORT: 6379
      SPRING_REDIS_PASSWORD: ${REDIS_PASSWORD}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: nextbill-kafka:29092
      NEXTBILL_EMAIL_USERNAME: ${NEXTBILL_EMAIL_USERNAME}
      NEXTBILL_EMAIL_PASSWORD: ${NEXTBILL_EMAIL_PASSWORD}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      JWT_SECRET: ${JWT_SECRET}
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    networks:
      - nextbill-network

  # Frontend (개발 서버 - 빌드 없음)
  nextbill-frontend-dev:
    image: node:18-alpine
    container_name: nextbill-frontend-dev
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - "3000:3000"
    networks:
      - nextbill-network
    depends_on:
      - nextbill-backend

volumes:
  mysql_data:
  redis_data:

networks:
  nextbill-network:
    driver: bridge
