spring:
  # 기본 프로파일 설정
  profiles:
    active: local
    
  # 데이터베이스 설정 (MySQL)
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  # JPA/Hibernate 설정
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false

  # OAuth2 설정 (Google 로그인)
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
            redirect-uri: ${GOOGLE_OAUTH2_REDIRECT_URI}
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v2/userinfo
            user-name-attribute: email

  # Mail 설정
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

  # Kafka 설정
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: nextbill-consumer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      
  # Redis 설정
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    database: 0
    timeout: 2000
    
  # 세션 설정 (OAuth2를 위한 세션 관리)
  session:
    store-type: memory
    timeout: 30m
    cookie:
      name: JSESSIONID
      max-age: 1800  # 30분
      secure: false  # 로컬에서는 false, 프로덕션에서는 true
      http-only: true
      same-site: none  # OAuth2 cross-origin 요청을 위해 none으로 설정
      path: /

# JWT 토큰 설정
jwt:
  secret: ${JWT_SECRET}
  access-expiration-ms: 3600000     # 1시간
  refresh-expiration-ms: 1209600000 # 14일

# 서버 설정
server:
  port: 8080

# 애플리케이션 설정
app:
  frontend:
    url: ${FRONTEND_URL}

# 로깅 설정
logging:
  level:
    suminjn.nextbill: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.web: DEBUG
